pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://chaquo.com/maven' }   // Chaquopy:Android 内嵌 Python 运行时
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://chaquo.com/maven' }
    }
}
rootProject.name = 'lanmeipai'
include ':app'
